<a href="https://colab.research.google.com/github/S4putri/221230005-Pengantar-ML/blob/main/Pratikum/Praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏋️ LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

DATA PREPROCESSING DENGAN NUMPY

In [2]:
import numpy as np

'''TODO: Implementasi Preprocessing Pipeline'''
# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)  # Supaya hasil random bisa direproduksi
X = np.random.randn(100, 5) * 10 + 5  # Data dengan mean ≈ 5, std ≈ 10


# TODO 1: Normalisasi Z-score: (x - mean) / std
def z_score_normalization(data):
    mean = np.mean(data, axis=0)   # rata-rata tiap fitur
    std = np.std(data, axis=0)     # standar deviasi tiap fitur
    normalized = (data - mean) / std
    return normalized

X_normalized = z_score_normalization(X)

# TODO 2: Handle outliers - replace values beyond 3 std with boundaries
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)   # mean tiap fitur
    std = np.std(data, axis=0)     # std tiap fitur

    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    cleaned = np.clip(data, lower_bound, upper_bound)
    return cleaned

X_cleaned = handle_outliers(X_normalized)

# TODO 3: One-hot encoding untuk label kategorikal
def one_hot_encoding(labels):
    classes, encoded = np.unique(labels, return_inverse=True)
    one_hot = np.zeros((labels.size, classes.size))
    one_hot[np.arange(labels.size), encoded] = 1
    return one_hot


labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)   # hasil one-hot encoding


# TODO 4: Train-test split manual
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]                # jumlah data
    n_test = int(n_samples * test_size)   # jumlah data test

    indices = np.random.permutation(n_samples)  # acak index
    test_idx = indices[:n_test]                 # ambil index test
    train_idx = indices[n_test:]                # ambil index train

    return X[train_idx], X[test_idx], y[train_idx], y[test_idx]


# Contoh label acak untuk split
y = np.random.randint(0, 3, 100)
X_train, X_test, y_train, y_test = train_test_split_numpy(X, y) # hasil spilt


# ✅ Validasi hasil
assert X_normalized.shape == X.shape, "Shape harus tetap sama"
assert np.allclose(X_normalized.mean(axis=0), 0, atol=1e-10), "Mean harus ~0 setelah z-score"
assert np.allclose(X_normalized.std(axis=0), 1, atol=1e-10), "Std harus ~1 setelah z-score"
assert len(X_train) + len(X_test) == len(X), "Jumlah data harus konsisten"

print("Original data shape:", X.shape)
print("Normalized data mean:", X_normalized.mean(axis=0).round(3))
print("Normalized data std:", X_normalized.std(axis=0).round(3))
print("One-hot labels shape:", one_hot_labels.shape)
print("One-hot labels:\n", one_hot_labels)
print("Train shape:", X_train.shape, "| Test shape:", X_test.shape)
print("✅ NumPy operations completed")

Original data shape: (100, 5)
Normalized data mean: [-0.  0. -0. -0.  0.]
Normalized data std: [1. 1. 1. 1. 1.]
One-hot labels shape: (7, 3)
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Train shape: (80, 5) | Test shape: (20, 5)
✅ NumPy operations completed
