<a href="https://colab.research.google.com/github/S4putri/221230005-Pengantar-ML/blob/main/week-02/latihan_praktikum_4_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏋️ LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

TENSOR OPERATIONS FOR NEURAL NETWORKS

In [5]:
import torch

'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)  # bobot linear layer
bias = torch.randn(1)  # bias linear layer

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return X @ W + b

output = linear_layer(X, weights, bias)
print(f"Input shape: {X.shape}")
print(f"Output (linear) shape: {output.shape}")
print("Linear output (first 5 rows):")
print(output[:5])

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.clamp(tensor, min=0)

activated = relu_activation(output)
print("\nReLU output (first 5 rows):")
print(activated[:5])

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, eps=1e-6):
    mean = tensor.mean(dim=0, keepdim=True)  # rata-rata per kolom
    std = tensor.std(dim=0, unbiased=False)  # standar deviasi per kolom
    return (tensor - mean) / (std + eps)

normalized = simple_batch_norm(X)
print("\nBatch normalized X (first 3 rows):")
print(normalized[:3])

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros((labels.size(0), num_classes))
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)
print(f"\nLabels: {labels}")
print("One-hot encoded labels:")
print(one_hot)

# Validasi hasil
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"

print("\n✅ Basic PyTorch operations completed")

### BONUS: ADVANCED TENSOR OPERATIONS ###
print("\n=== ADVANCED MATRIX MULTIPLICATION ===")

def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    m, n = A.shape
    _, p = B.shape
    result = torch.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Manual multiplication result:\n", manual_result)
print("Torch matmul result:\n", torch_result)
print("Results equal:", torch.allclose(manual_result, torch_result))

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"

print("\n✅ Advanced tensor operations completed")

=== BASIC NEURAL NETWORK OPERATIONS ===
Input shape: torch.Size([32, 10])
Output (linear) shape: torch.Size([32, 1])
Linear output (first 5 rows):
tensor([[-1.4343],
        [ 1.3122],
        [-0.1737],
        [ 2.5986],
        [-1.2484]])

ReLU output (first 5 rows):
tensor([[0.0000],
        [1.3122],
        [0.0000],
        [2.5986],
        [0.0000]])

Batch normalized X (first 3 rows):
tensor([[-1.2206, -0.8825, -0.5326,  1.6283, -0.3218,  1.4313,  0.8448, -0.3315,
          0.8861, -0.4999],
        [ 0.6573, -1.1429,  0.0411, -0.7486,  0.0882,  1.1961, -0.3367, -1.9023,
         -1.7624,  0.4327],
        [-0.9180, -0.0416, -0.4627, -0.5545, -0.2510, -1.3733,  1.5702, -0.4012,
         -0.7397,  0.0391]])

Labels: tensor([2, 1, 0, 0, 1, 1, 1, 0, 1, 2])
One-hot encoded labels:
tensor([[0., 0., 1.],
        [0., 1., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.],
   