<a href="https://colab.research.google.com/github/S4putri/221230005-Pengantar-ML/blob/main/week-02/latihan_praktikum_4_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏋️ LATIHAN 4: OPERASI PYTORCH UNTUK DEEP LEARNING

TENSOR OPERATIONS FOR NEURAL NETWORKS

In [1]:
import torch

'''TODO: Implementasi Operasi Dasar Neural Networks'''
# Simulasi batch data: 32 samples, 10 features
batch_size, n_features = 32, 10
X = torch.randn(batch_size, n_features)
weights = torch.randn(n_features, 1)  # bobot linear layer
bias = torch.randn(1)  # bias linear layer

# TODO 1: Implementasi linear layer manual: y = XW + b
def linear_layer(X, W, b):
    return X @ W + b

output = linear_layer(X, weights, bias)
print(f"Input shape: {X.shape}")
print(f"Output (linear) shape: {output.shape}")
print("Linear output (first 5 rows):")
print(output[:5])

# TODO 2: Implementasi ReLU activation function
def relu_activation(tensor):
    return torch.clamp(tensor, min=0)

activated = relu_activation(output)
print("\nReLU output (first 5 rows):")
print(activated[:5])

# TODO 3: Batch normalization sederhana
def simple_batch_norm(tensor, eps=1e-6):
    mean = tensor.mean(dim=0, keepdim=True)  # rata-rata per kolom
    std = tensor.std(dim=0, unbiased=False)  # standar deviasi per kolom
    return (tensor - mean) / (std + eps)

normalized = simple_batch_norm(X)
print("\nBatch normalized X (first 3 rows):")
print(normalized[:3])

# TODO 4: One-hot encoding manual
def one_hot_pytorch(labels, num_classes):
    one_hot = torch.zeros((labels.size(0), num_classes))
    one_hot[torch.arange(labels.size(0)), labels] = 1
    return one_hot

labels = torch.randint(0, 3, (10,))
one_hot = one_hot_pytorch(labels, num_classes=3)
print(f"\nLabels: {labels}")
print("One-hot encoded labels:")
print(one_hot)

# Validasi hasil
assert output.shape == (batch_size, 1), "Linear output shape incorrect"
assert torch.all(activated >= 0), "ReLU should be >= 0"
assert normalized.shape == X.shape, "Batch norm should preserve shape"
assert one_hot.shape == (10, 3), "One-hot shape incorrect"

print("\n✅ Basic PyTorch operations completed")

### BONUS: ADVANCED TENSOR OPERATIONS ###
print("\n=== ADVANCED MATRIX MULTIPLICATION ===")

def manual_matrix_multiply(A, B):
    """
    Implementasi perkalian matriks manual tanpa torch.matmul
    """
    m, n = A.shape
    _, p = B.shape
    result = torch.zeros((m, p))
    for i in range(m):
        for j in range(p):
            for k in range(n):
                result[i, j] += A[i, k] * B[k, j]
    return result

# Test dengan matriks kecil
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

manual_result = manual_matrix_multiply(A, B)
torch_result = torch.matmul(A, B)

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Manual multiplication result:\n", manual_result)
print("Torch matmul result:\n", torch_result)
print("Results equal:", torch.allclose(manual_result, torch_result))

assert torch.allclose(manual_result, torch_result), "Manual multiplication incorrect"

print("\n✅ Advanced tensor operations completed")

Input shape: torch.Size([32, 10])
Output (linear) shape: torch.Size([32, 1])
Linear output (first 5 rows):
tensor([[ 2.1569],
        [-0.2606],
        [ 1.2118],
        [ 1.1306],
        [ 0.7490]])

ReLU output (first 5 rows):
tensor([[2.1569],
        [0.0000],
        [1.2118],
        [1.1306],
        [0.7490]])

Batch normalized X (first 3 rows):
tensor([[-0.8705,  0.8924, -0.4577,  1.4309, -0.2295, -0.6390, -1.1909, -0.7158,
          0.1988,  0.7427],
        [-0.4790, -0.1789,  0.7598,  1.1187,  1.4186, -0.7201,  0.3830, -0.3769,
          0.3429, -1.0104],
        [-0.3524,  1.5176, -0.2744, -0.2883,  1.6530,  0.3939, -0.8949,  1.4544,
         -0.5181,  0.1973]])

Labels: tensor([1, 0, 2, 0, 0, 2, 0, 2, 1, 2])
One-hot encoded labels:
tensor([[0., 1., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [1., 0., 0.],
        [0., 0., 1.],
        [1., 0., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.]])

✅ Basic PyTorch ope